dependencies {
	implementation platform(libs.spring.boot.dependencies)
	implementation 'org.springframework.boot:spring-boot-starter-web'
	implementation 'jakarta.validation:jakarta.validation-api:3.0.2'
	implementation 'org.hibernate.validator:hibernate-validator'
	compileOnly 'org.projectlombok:lombok'
	implementation 'org.modelmapper:modelmapper:3.2.5'
}
