dependencies {
	implementation platform(libs.spring.boot.dependencies)
	implementation 'org.springframework.boot:spring-boot-starter-web'
	implementation 'org.springframework.boot:spring-boot-starter-webflux'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
	implementation 'org.apache.httpcomponents.client5:httpclient5'
	annotationProcessor libs.lombok
	compileOnly libs.lombok
}
