dependencies {

    implementation platform(libs.spring.boot.dependencies)

    implementation 'org.springframework.boot:spring-boot-starter-data-redis'

    implementation 'org.apache.commons:commons-pool2'

    implementation 'com.fasterxml.jackson.datatype:jackson-datatype-jsr310'

    compileOnly 'org.springframework.boot:spring-boot-autoconfigure'

    compileOnly libs.lombok
    annotationProcessor libs.lombok

}
